name: Karma
version: ${project.version}
description: TODO
load: STARTUP
authors:
  - AspyTheAussie
website: https://github.com/blockcade/karma-minecraft
main: net.blockcade.karma.Minecraft.Karma

softdepend:
  - LiteBans