name: Karma
version: ${project.version}
api-version: 1.13
description: TODO
load: POSTWORLD
authors:
  - AspyTheAussie
website: https://github.com/blockcade/karma-minecraft
main: net.blockcade.karma.Minecraft.Karma

softdepend:
  - LiteBans